### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by epadams** [tnychn/instascrape#16] opened 2020-12-09 22:08 UTC
I am unable to login to my account, and help with this issue would be appreciated.
I am using Python 3.8.6, and instascrape 2.0.3.post1.

(1) + [Login New Account]

(1-1)choice> 1
Username:
Password:
Traceback (most recent call last):
  File "/home/ethan/.local/bin/instascrape", line 8, in <module>
    sys.exit(main())
  File "/home/ethan/.local/lib/python3.8/site-packages/instascrape/__main__.py", line 196, in main
    args.func(**vars(args))
  File "/home/ethan/.local/lib/python3.8/site-packages/instascrape/commands/login.py", line 65, in login_handler
    insta.login(username, password, load_cookie(cookie_name) if cookie_name else None)
  File "/home/ethan/.local/lib/python3.8/site-packages/instascrape/instascrape.py", line 114, in login
    data = resp.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tnychn** [comment] 2020-12-10 12:35
Duplicate of #2.

**Closed by tnychn** 2020-12-10 12:35 UTC
