### ISSUE TITLE
 Unable to login - JSONDecodeError

### ISSUE THREAD

**Issue by stupidhead69** [tnychn/instascrape#14] opened 2020-09-05 02:49 UTC
I'm probably doing something wrong, installed using python3 on macOS catalina.

`ERROR  JSONDecodeError: Expecting value: line 1 column 1 (char 0)
      File "/Library/Frameworks/Python.framework/Versions/3.7/bin/instascrape", line 11, in <module>
    load_entry_point('instascraper==2.0.3.post1', 'console_scripts', 'instascrape')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instascraper-2.0.3.post1-py3.7.egg/instascrape/__main__.py", line 196, in main
    args.func(**vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instascraper-2.0.3.post1-py3.7.egg/instascrape/commands/login.py", line 65, in login_handler
    insta.login(username, password, load_cookie(cookie_name) if cookie_name else None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instascraper-2.0.3.post1-py3.7.egg/instascrape/instascrape.py", line 114, in login
    data = resp.json()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests-2.24.0-py3.7.egg/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
`

**Comment by nershman** [comment] 2020-09-21 04:55
I'm having the same issue.

(1) + [Login New Account]

(1-1)choice> 1
Username:
Password: 
- Logging in...
    getting cookie by username and password
 ERROR  JSONDecodeError: Expecting value: line 1 column 1 (char 0)
      File "/usr/local/bin/instascrape", line 11, in <module>
    load_entry_point('instascraper==2.0.3.post1', 'console_scripts', 'instascrape')()
  File "/usr/local/lib/python3.7/site-packages/instascrape/__main__.py", line 196, in main
    args.func(**vars(args))
  File "/usr/local/lib/python3.7/site-packages/instascrape/commands/login.py", line 65, in login_handler
    insta.login(username, password, load_cookie(cookie_name) if cookie_name else None)
  File "/usr/local/lib/python3.7/site-packages/instascrape/instascrape.py", line 114, in login
    data = resp.json()
  File "/Library/Python/3.7/lib/python/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Python/3.7/lib/python/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Library/Python/3.7/lib/python/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Library/Python/3.7/lib/python/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())

Traceback (most recent call last):
  File "/usr/local/bin/instascrape", line 11, in <module>
    load_entry_point('instascraper==2.0.3.post1', 'console_scripts', 'instascrape')()
  File "/usr/local/lib/python3.7/site-packages/instascrape/__main__.py", line 196, in main
    args.func(**vars(args))
  File "/usr/local/lib/python3.7/site-packages/instascrape/commands/login.py", line 65, in login_handler
    insta.login(username, password, load_cookie(cookie_name) if cookie_name else None)
  File "/usr/local/lib/python3.7/site-packages/instascrape/instascrape.py", line 114, in login
    data = resp.json()
  File "/Library/Python/3.7/lib/python/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Python/3.7/lib/python/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Library/Python/3.7/lib/python/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Library/Python/3.7/lib/python/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tnychn** [comment] 2020-09-22 02:42
Possible duplicate of #2.

**Closed by tnychn** 2020-09-22 02:42 UTC
Labels: bug, duplicate

**Comment by epadams** [comment] 2020-12-09 21:26
I am having a similar issue.

    Saved Cookies

(1) + [Login New Account]

(1-1)choice> 1
Username:
Password:
Traceback (most recent call last):
  File "/home/ethan/.local/bin/instascrape", line 8, in <module>
    sys.exit(main())
  File "/home/ethan/.local/lib/python3.8/site-packages/instascrape/__main__.py", line 196, in main
    args.func(**vars(args))
  File "/home/ethan/.local/lib/python3.8/site-packages/instascrape/commands/login.py", line 65, in login_handler
    insta.login(username, password, load_cookie(cookie_name) if cookie_name else None)
  File "/home/ethan/.local/lib/python3.8/site-packages/instascrape/instascrape.py", line 114, in login
    data = resp.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any help would be appreciated.
