### ISSUE TITLE
KeyError : csrftoken

### ISSUE THREAD

**Issue by mickelastrologer** [tnychn/instascrape#15] opened 2020-11-22 12:54 UTC
![IMG_20201122_180858](https://user-images.githubusercontent.com/74862455/99904250-c642bb00-2cef-11eb-9d5d-8ad95348008c.jpg)

**Comment by tnychn** [comment] 2020-11-22 21:14
Duplicate of #2.

**Closed by tnychn** 2020-11-22 21:14 UTC
Labels: bug, duplicate

**Comment by mickelastrologer** [comment] 2020-11-25 12:58
@tnychn give me the solution

**Comment by NOBHACKER120** [comment] 2022-03-06 05:41
I tried #2 but not working also
